-- Статистика бросков кубика
-- Создание таблицы бросков
CREATE TABLE DiceRolls (
    roll_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dice_value INTEGER,
    roll_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Симуляция 1000 бросков кубика (1-6)
INSERT INTO DiceRolls (dice_value)
SELECT RANDOM(1, 6) FROM GENERATE_SERIES(1, 1000);

-- Анализ распределения
SELECT
    dice_value,
    COUNT(*) AS frequency,
    (COUNT(*) / 1000.0) * 100 AS percentage
FROM DiceRolls
GROUP BY dice_value
ORDER BY dice_value;