-- Случайные пользователи
-- Создание таблицы пользователей
CREATE TABLE Users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50),
    age INTEGER,
    registration_date DATE
);

-- Заполнение случайными данными
INSERT INTO Users (username, age, registration_date)
SELECT 
    'user' || RANDOM(1000, 9999), -- Имя вида user1234
    RANDOM(18, 80),               -- Возраст 18-80
    CURRENT_DATE - RANDOM(0, 1095) -- Дата за последние 3 года
FROM GENERATE_SERIES(1, 100);

-- Просмотр первых 10 пользователей
SELECT * FROM Users LIMIT 10;