-- Тестовые данные для продуктов
-- Создание таблицы продуктов
CREATE TABLE Products (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(100),
    price DECIMAL(10, 2),
    stock_quantity INTEGER,
    category_id INTEGER
);

-- Заполнение случайными данными
INSERT INTO Products (product_name, price, stock_quantity, category_id)
SELECT 
    'Product ' || n,
    (RANDOM(10, 1000) / 10.0)::DECIMAL(10,2), -- Цена от 1.0 до 100.0
    RANDOM(0, 500),                            -- Количество от 0 до 500
    RANDOM(1, 10)                              -- Категория от 1 до 10
FROM GENERATE_SERIES(1, 50) AS n;

-- Просмотр первых 10 записей
SELECT * FROM Products LIMIT 10;