-- Случайные даты для заказов
-- Создание таблицы заказов
CREATE TABLE random_orders (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER,
    order_date DATE,
    amount DECIMAL(10, 2)
);

-- Заполнение случайными данными
INSERT INTO random_orders (customer_id, order_date, amount)
SELECT 
    RANDOM(1, 100), -- ID клиента от 1 до 100
    CURRENT_DATE - RANDOM(0, 365)::INTEGER, -- Дата за последний год
    (RANDOM(100, 10000) / 100.0)::DECIMAL(10,2) -- Сумма от 1.00 до 100.00
FROM GENERATE_SERIES(1, 200);

-- Просмотр первых 10 заказов
SELECT * FROM random_orders ORDER BY order_date LIMIT 10;